### ISSUE TITLE
Support for text-based config file

### ISSUE THREAD

**Issue by avrelaun** [Keruspe/Germinal#13]
Currently Germinal is configured via Gsettings and it works well with instantaneous changes of the config.

But for those of us not running the GNOME stack (sway in my case but any tiling wm is the same) and/or managing our dotfiles via git so it can be easily shared accross machines, a simple config file in $XDG_CONFIG_HOME/Germinal/config would be awesome.

The logic could be: Use Gsettings if no config file is present, override if present.

**Comment by sardemff7** [comment]
A simpler approach could be to use GSettings KeyFile backend.
I never tested it (and still I am using i3 ;-) ) but it should either be as simple as exporting `G_SETTINGS_BACKEND=keyfile` or require a small change in Germinal to explicitly request that backend (based on whatever condition feels best).

**Comment by Keruspe** [comment]
I see two "simple" possibilities here:

- GSettings KeyFile backend is worth a shot. I'll try to see if I can make the switch automagical
- Detecting at startup if the config file exist, store its values into dconf and using dconf as we currently do.

I'd be ok with those two, but I won't ever do hot reloading of configuration based on the filesystem. It's just not reliable.

**Comment by Keruspe** [comment]
Actually the first one should be quite easy to implement, will do it later
