### ISSUE TITLE
Germinal won't kill subprocess on SIGTERM

### ISSUE THREAD

**Issue by avrelaun** [Keruspe/Germinal#14]
I switched to Germinal full-time since I discovered it has the killer urxvt feature that was missing from Termite: client/daemon mode, all new terminal shells spawn as child of Germinal making it more lightweight.

I must say that I use Geminal with 'zsh' as startup command since I find tmux redundant with my tiling wm sway, launching tmux only on long-running processes and remote applications.

However I just found out than when I kill a terminal window using sway (sending a SITINT and a SIGTERM), the window closes but the zsh subprocess keeps on living as a zombie, keeping whatever program running at the time running and consuming ressources.

**Comment by Keruspe** [comment]
That’s interesting, will give it a look.

Why do you kill the window instead of just closing it though?

**Comment by avrelaun** [comment]
In tiling wm we do not have graphical buttons to close a window.
The standard keybinding for closing windows on i3 and sway is $mod+Shift+q, and I have the same behaviour on both.
 
Here's the relevant part from i3 user guide: https://i3wm.org/docs/userguide.html#_closing_windows

I may be wrong on the SIGINT / SIGTERM I found on the sway code, I think they are related to the main sway process. Here's the sway code responsible of closing windows: https://github.com/swaywm/sway/blob/master/sway/commands/kill.c

**Comment by Keruspe** [comment]
Ok, I think I know why. Will try fixing it soon
