### ISSUE TITLE
Makefile: 1612: *** missing separator.  Stop.

### ISSUE THREAD

**Issue by guotsuan** [Keruspe/Germinal#3]
When I compile the newest git version of germinal, I got a error "Makefile: 1612: *** missing separator.  Stop.".  I have not problem in compiling Germinal-14. So I guess than there may be an error or my version of tools are not right.

The corresponding part of Makefile looks like:

========================================================================
%.xml:       %.xml.in       $(INTLTOOL_MERGE) ; $(INTLTOOL_V_MERGE)LC_ALL=C $(INTLTOOL_MERGE) $(INTLTOOL_V_MERGE_OPTIONS) -x -u --no-translations $< $@

@APPSTREAM_XML_RULES@
%.xml:       %.xml.in       $(INTLTOOL_MERGE) $(wildcard $(top_srcdir)/po/*.po) ; $(INTLTOOL_V_MERGE)LC_ALL=C $(INTLTOOL_MERGE) $(INTLTOOL_V_MERGE_OPTIONS) -x -u -c $(top_builddir)/po/.intltool-merge-cache $(top_srcdir)/po $< $@
.dbus.in.service:
	@ $(MKDIR_P) data/dbus
	$(AM_V_GEN) $(SED)                  \
	    -e 's,[@]bindir[@],$(bindir),g' \
	    <$^ >$@

%.desktop:   %.desktop.in   $(INTLTOOL_MERGE) $(wildcard $(top_srcdir)/po/*.po) ; $(INTLTOOL_V_MERGE)LC_ALL=C $(INTLTOOL_MERGE) $(INTLTOOL_V_MERGE_OPTIONS) -d -u -c $(top_builddir)/po/.intltool-merge-cache $(top_srcdir)/po $< $@
.desktop.in.in.desktop.in:
	@ $(MKDIR_P) data/desktop
	$(AM_V_GEN) $(SED)                  \
	    -e 's,[@]bindir[@],$(bindir),g' \
	    <$^ >$@

===========================================================================
I see that $(INTLTOOL_MERGE)... etc should in a new started line with hard table. 
But I'm not sure about what is @APPSTREAM_XML_RULES@

The version of my tools
intltoolize (GNU intltool) 0.51.0
autoconf autoconf (GNU Autoconf) 2.69
Let me know if I can further help

Best regards,

Quan

**Comment by Keruspe** [comment]
Hi,

You need appstream-glib in order to build from git.

**Comment by guotsuan** [comment]
I see. It works now. Thank you!
