### ISSUE TITLE
Decorated window on i3wm

### ISSUE THREAD

**Issue by Kdecherf** [Keruspe/Germinal#6]
Germinal v17 introduces a "bug" on i3wm: the window becomes borderless which is confusing when having several terminals on the same workspace.

After comparing v16 and v17 it appears that the behavior comes from the fix introduced by e60c5374a18a8365c6ed949158c87318770808f4. This commit has, in fact, fixed another issue: `gtk_window_set_decorated (win, FALSE)` was ignored because it was called after `gtk_widget_show_all`.

Could you please add a config option to prevent Germinal from disabling decoration?

**Comment by Keruspe** [comment]
Actually, it always was supposed to be decoration-less (and it always has been here), but I sure can add such a setting.

**Comment by Kdecherf** [comment]
Perfect, thanks for the config option!

Just a quick note that you pushed a little typo, see my comment on the commit.
