### ISSUE TITLE
Tmux cannot set Germinal window title

### ISSUE THREAD

**Issue by rhabbachi** [Keruspe/Germinal#7]
I've been using Germinal as my main terminal emulator for quite some time now. Thank you for this great project!

One thing That I'm missing from the old Gnome Terminal/Tmux config is the ability to update the window title with the session name. I have this config on my `tmux.conf` file

```
# Terminal emulator window titles
set -g set-titles on
set -g set-titles-string "#H-#S"
```

Any way to get this working again?

**Comment by Keruspe** [comment]
Hi,

I'm not sure to understand what this is supposed to do.
I'm willing to make it work, but can you tell me how to check the actual result, and what is expected instead?

**Comment by rhabbachi** [comment]
Yeah I did a poor job explaining it.
See the following screenshot

![image](https://cloud.githubusercontent.com/assets/1914306/19636905/5741d7aa-99cc-11e6-897f-7af73d8bb8d7.png)

In the left an Xterm window, on the right Germinal window. Both `tmux attach`ed to the same session.

Xterm updates the window title to match the `set-titles-string` configuration (hostname - session_name). But Germinal ignores that.

**Comment by Keruspe** [comment]
@rhabbachi Should be fixed in Germinal 20

**Comment by rhabbachi** [comment]
Thanks!
![image](https://user-images.githubusercontent.com/1914306/32047696-ba0fbe36-ba3e-11e7-90c5-992997dcc6a8.png)
