### ISSUE TITLE
How are colors/themes set? 

### ISSUE THREAD

**Issue by CrashyBang** [Keruspe/Germinal#8]
It would be good it colorscheme could be read from something like `~/.Xresources` or even better something like `~/.config/germinal/colors/schemename` without the need to recompile. 

Also would be good to be able to set font families, sizes, etc... 

Thoughts?

**Comment by sardemff7** [comment]
You can already set them (even at runtime) using `gsettings set org.gnome.Germinal palette` or `dconf-editor`.

**Comment by Keruspe** [comment]
Yup, open up dconf-editor and navigate to org/gnome/Germinal and you'll find everything. All the config is updated without the need to restart germinal

**Comment by CrashyBang** [comment]
Hey @sardemff7 & @Keruspe,

Out of curiosity what would be your thoughts on allowing Germinal to be configured by an rc file similar to [svte](https://github.com/mutantturkey/svte/blob/master/example_svterc)?

I only ask because it makes the whole *set up* more portable and seems to fit in nicely with the projects philosophy (i.e. using `tmux` by default which is also configured using dot-files).

Let me know your thoughts.

**Comment by sardemff7** [comment]
That would duplicate the feature. GSettings can use a different backend if you want, just find one, or make ore. :-)
